name: compute version
description: Computes the various versions using the Git history.
inputs:
  configFilePath:
    default: 'GitVersion.yml'
    description: The GitVersion configuration file.
    required: true
outputs:
  assemblyVersion:
    description: The assembly version for the shared components
    value: ${{ steps.version.outputs.GitVersion_AssemblySemVer }}
  fileVersion:
    description: The assembly file version for the shared components
    value: ${{ steps.version.outputs.GitVersion_AssemblySemFileVer }}
  informationalVersion:
    description: The assembly informational version for the shared components
    value: ${{ steps.version.outputs.GitVersion_InformationalVersion }}
  nugetVersion:
    description: The NuGet package version for the shared components
    value: ${{ steps.version.outputs.GitVersion_SemVer }}

runs:
  using: composite
  steps:
  - name: Install GitVersion
    uses: gittools/actions/gitversion/setup@v0.13.4
    with:
      versionSpec: '5.x'

  - name: Determine Version
    id: version
    uses: gittools/actions/gitversion/execute@v0.13.4
    with:
      configFilePath: ${{ inputs.configFilePath }}
      targetPath: ${{ github.workspace }}
      useConfigFile: true
