# Configuration based on https://help.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "America/Los_Angeles"
    ignore:
      - dependency-name: "Microsoft.IdentityModel.*"
        # Ignore all Dependabot updates for version >= 7.0.0
        versions: ["7.*"]
    open-pull-requests-limit: 30

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 30
