<Project Sdk="MSTest.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(SupportedFrameworks)</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Medino" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="NSubstitute" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Microsoft.Health.Extensions.DependencyInjection\Microsoft.Health.Extensions.DependencyInjection.csproj" />
    <ProjectReference Include="..\Microsoft.Health.SqlServer\Microsoft.Health.SqlServer.csproj" />
    <ProjectReference Include="..\Microsoft.Health.SqlServer.Api\Microsoft.Health.SqlServer.Api.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Controllers\Migrations\1.sql" />
  </ItemGroup>

</Project>
