<Project Sdk="MSTest.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(SupportedFrameworks)</TargetFrameworks>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Microsoft.Health.Operations\Microsoft.Health.Operations.csproj" />
  </ItemGroup>

</Project>
