name: dotnet publish
description: Pushes the packages to the NuGet feed and the symbols to the Azure DevOps symbol server.
inputs:
  buildConfiguration:
    default: Debug
    description: The dotnet build configuration
    required: false
  nugetFeed:
    default: 'https://microsofthealthoss.pkgs.visualstudio.com/FhirServer/_packaging/Public/nuget/v3/index.json'
    description: The NuGet feed for the packages
    required: false
  packageFolder:
    description: The folder for generated NuGet packages
    required: true
  packageVersion:
    description: The NuGet package version
    required: true
  symbolsAccountName:
    default: microsofthealthoss
    description: The Azure DevOps account name containing the symbol server
    required: false

runs:
  using: composite
  steps:
  - name: dotnet pack
    shell: bash
    run: |
      dotnet pack "./Microsoft.Health.slnx" \
        -c "${{ inputs.buildConfiguration }}" \
        "-p:ContinuousIntegrationBuild=true" \
        "-p:PackageVersion=${{ inputs.packageVersion }}" \
        --no-build \
        -o "${{ inputs.packageFolder }}"

  - name: Upload Packages
    uses: actions/upload-artifact@v6
    with:
      name: packages
      path: ${{ inputs.packageFolder }}

  # GUID below is for Azure DevOps: https://learn.microsoft.com/en-us/azure/devops/organizations/accounts/manage-personal-access-tokens-via-api?view=azure-devops
  - name: Fetch Token
    id: az-account
    uses: azure/CLI@v2
    with:
      azcliversion: latest
      inlineScript: |
        token=$(az account get-access-token --resource 499b84ac-1321-427f-aa17-267ca6975798 --query accessToken --output tsv)
        echo "::add-mask::$token"
        echo "access-token=$token" >> "$GITHUB_OUTPUT"

  - name: Authenticate NuGet
    uses: actions/setup-dotnet@v5
    with:
      source-url: '${{ inputs.nugetFeed }}'
    env:
      NUGET_AUTH_TOKEN: ${{ steps.az-account.outputs.access-token }}

  - name: dotnet nuget push
    shell: bash
    run: dotnet nuget push ${{ inputs.packageFolder }}/*.nupkg --api-key AzureArtifacts --skip-duplicate

  - name: Publish Symbols
    uses: microsoft/action-publish-symbols@v2.1.6
    with:
      accountName: ${{ inputs.symbolsAccountName }}
      personalAccessToken: ${{ steps.az-account.outputs.access-token }}
      symbolServiceUrl: 'https://artifacts.dev.azure.com'
