//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Microsoft.Health.SqlServer.Web.Features.Schema.Model
{
    using Microsoft.Health.SqlServer.Features.Client;
    using Microsoft.Health.SqlServer.Features.Schema.Model;

    internal class ComplexNumber1TableValuedParameterDefinition : TableValuedParameterDefinition<ComplexNumber1Row>
    {
        internal ComplexNumber1TableValuedParameterDefinition(System.String parameterName) : base(parameterName, "dbo.ComplexNumber_1")
        {
        }

        internal readonly NVarCharColumn A = new NVarCharColumn("A", 128);
        internal readonly NVarCharColumn B = new NVarCharColumn("B", 128);

        protected override global::System.Collections.Generic.IEnumerable<Column> Columns => new Column[] { A, B };

        protected override void FillSqlDataRecord(global::Microsoft.Data.SqlClient.Server.SqlDataRecord record, ComplexNumber1Row rowData)
        {
            A.Set(record, 0, rowData.A);
            B.Set(record, 1, rowData.B);
        }
    }

    internal struct ComplexNumber1Row
    {
        internal ComplexNumber1Row(System.String A, System.String B)
        {
            this.A = A;
            this.B = B;
        }

        internal System.String A { get; }
        internal System.String B { get; }
    }

    internal class NameType1TableValuedParameterDefinition : TableValuedParameterDefinition<NameType1Row>
    {
        internal NameType1TableValuedParameterDefinition(System.String parameterName) : base(parameterName, "dbo.NameType_1")
        {
        }

        internal readonly NVarCharColumn Given = new NVarCharColumn("Given", 128);
        internal readonly NVarCharColumn Family = new NVarCharColumn("Family", 128);

        protected override global::System.Collections.Generic.IEnumerable<Column> Columns => new Column[] { Given, Family };

        protected override void FillSqlDataRecord(global::Microsoft.Data.SqlClient.Server.SqlDataRecord record, NameType1Row rowData)
        {
            Given.Set(record, 0, rowData.Given);
            Family.Set(record, 1, rowData.Family);
        }
    }

    internal struct NameType1Row
    {
        internal NameType1Row(System.String Given, System.String Family)
        {
            this.Given = Given;
            this.Family = Family;
        }

        internal System.String Given { get; }
        internal System.String Family { get; }
    }

    internal class NameType2TableValuedParameterDefinition : TableValuedParameterDefinition<NameType2Row>
    {
        internal NameType2TableValuedParameterDefinition(System.String parameterName) : base(parameterName, "dbo.NameType_2")
        {
        }

        internal readonly NVarCharColumn Given = new NVarCharColumn("Given", 128);
        internal readonly NVarCharColumn Family = new NVarCharColumn("Family", 128);

        protected override global::System.Collections.Generic.IEnumerable<Column> Columns => new Column[] { Given, Family };

        protected override void FillSqlDataRecord(global::Microsoft.Data.SqlClient.Server.SqlDataRecord record, NameType2Row rowData)
        {
            Given.Set(record, 0, rowData.Given);
            Family.Set(record, 1, rowData.Family);
        }
    }

    internal struct NameType2Row
    {
        internal NameType2Row(System.String Given, System.String Family)
        {
            this.Given = Given;
            this.Family = Family;
        }

        internal System.String Given { get; }
        internal System.String Family { get; }
    }
}