//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Microsoft.Health.SqlServer.Web.Features.Schema.Model
{
    using Microsoft.Health.SqlServer.Features.Client;
    using Microsoft.Health.SqlServer.Features.Schema.Model;

    internal class VLatest
    {
        internal readonly static InsertNumbersProcedure InsertNumbers = new InsertNumbersProcedure();
        internal readonly static MyProcedureProcedure MyProcedure = new MyProcedureProcedure();

        internal class InsertNumbersProcedure : StoredProcedure
        {
            internal InsertNumbersProcedure() : base("dbo.InsertNumbers")
            {
            }

            private readonly ComplexNumberV1TableValuedParameterDefinition _names = new ComplexNumberV1TableValuedParameterDefinition("@names");

            public void PopulateCommand(SqlCommandWrapper command, global::System.Collections.Generic.IEnumerable<ComplexNumberV1Row> names)
            {
                command.CommandType = global::System.Data.CommandType.StoredProcedure;
                command.CommandText = "dbo.InsertNumbers";
                _names.AddParameter(command.Parameters, names);
            }

            public void PopulateCommand(SqlCommandWrapper command, InsertNumbersTableValuedParameters tableValuedParameters)
            {
                PopulateCommand(command, names: tableValuedParameters.Names);
            }
        }

        internal class InsertNumbersTvpGenerator<TInput> : IStoredProcedureTableValuedParametersGenerator<TInput, InsertNumbersTableValuedParameters>
        {
            public InsertNumbersTvpGenerator(ITableValuedParameterRowGenerator<TInput, ComplexNumberV1Row> ComplexNumberV1RowGenerator)
            {
                this.ComplexNumberV1RowGenerator = ComplexNumberV1RowGenerator;
            }

            private readonly ITableValuedParameterRowGenerator<TInput, ComplexNumberV1Row> ComplexNumberV1RowGenerator;

            public InsertNumbersTableValuedParameters Generate(TInput input)
            {
                return new InsertNumbersTableValuedParameters(ComplexNumberV1RowGenerator.GenerateRows(input));
            }
        }

        internal struct InsertNumbersTableValuedParameters
        {
            internal InsertNumbersTableValuedParameters(global::System.Collections.Generic.IEnumerable<ComplexNumberV1Row> Names)
            {
                this.Names = Names;
            }

            internal global::System.Collections.Generic.IEnumerable<ComplexNumberV1Row> Names { get; }
        }

        internal class MyProcedureProcedure : StoredProcedure
        {
            internal MyProcedureProcedure() : base("dbo.MyProcedure_2")
            {
            }

            private readonly NameTypeV1TableValuedParameterDefinition _names = new NameTypeV1TableValuedParameterDefinition("@names");

            public void PopulateCommand(SqlCommandWrapper command, global::System.Collections.Generic.IEnumerable<NameTypeV1Row> names)
            {
                command.CommandType = global::System.Data.CommandType.StoredProcedure;
                command.CommandText = "dbo.MyProcedure_2";
                _names.AddParameter(command.Parameters, names);
            }

            public void PopulateCommand(SqlCommandWrapper command, MyProcedureTableValuedParameters tableValuedParameters)
            {
                PopulateCommand(command, names: tableValuedParameters.Names);
            }
        }

        internal class MyProcedureTvpGenerator<TInput> : IStoredProcedureTableValuedParametersGenerator<TInput, MyProcedureTableValuedParameters>
        {
            public MyProcedureTvpGenerator(ITableValuedParameterRowGenerator<TInput, NameTypeV1Row> NameTypeV1RowGenerator)
            {
                this.NameTypeV1RowGenerator = NameTypeV1RowGenerator;
            }

            private readonly ITableValuedParameterRowGenerator<TInput, NameTypeV1Row> NameTypeV1RowGenerator;

            public MyProcedureTableValuedParameters Generate(TInput input)
            {
                return new MyProcedureTableValuedParameters(NameTypeV1RowGenerator.GenerateRows(input));
            }
        }

        internal struct MyProcedureTableValuedParameters
        {
            internal MyProcedureTableValuedParameters(global::System.Collections.Generic.IEnumerable<NameTypeV1Row> Names)
            {
                this.Names = Names;
            }

            internal global::System.Collections.Generic.IEnumerable<NameTypeV1Row> Names { get; }
        }
    }
}