name: github release
description: Creates a GitHub release for the shared packages.
inputs:
  commitSha:
    description: The commit SHA associated with the tag and the release
    required: true
  gitHubToken:
    description: Personal Access Token (PAT) for GitHub used to create the release
    required: true
  packageFolder:
    description: The folder for generated NuGet packages
    required: true
  repository:
    description: The GitHub repository that will contain the release
    required: true
  tag:
    description: The Git tag to create and associate with the release
    required: true
  title:
    description: The title for the GitHub release
    required: true

runs:
  using: composite
  steps:
  - name: Release
    shell: bash
    run: |
      gh release create "${{ inputs.tag }}" \
        --repo "${{ inputs.repository }}" \
        --target ${{ inputs.commitSha }} \
        --title "${{ inputs.title }}" \
        --generate-notes

      for pkg in ${{ inputs.packageFolder }}/*.nupkg; do
          gh release upload "${{ inputs.tag }}" $pkg --repo "${{ inputs.repository }}" --clobber
      done
    env:
      GITHUB_TOKEN: ${{ inputs.gitHubToken }}
