name: github release
description: Creates a GitHub release for the shared packages.
inputs:
  commitSha:
    description: The commit SHA associated with the tag and the release
    required: true
  gitHubToken:
    description: Personal Access Token (PAT) for GitHub used to create the release
    required: true
  packageFolder:
    description: The folder for generated NuGet packages
    required: true
  repository:
    description: The GitHub repository that will contain the release
    required: true
  tag:
    description: The Git tag to create and associate with the release
    required: true
  title:
    description: The title for the GitHub release
    required: true

runs:
  using: composite
  steps:
  - name: Release
    shell: bash
    run: |
      # Read first line of title
      readarray -t lines <<< "$RELEASE_TITLE"

      gh release create "$RELEASE_TAG" \
        --repo "$REPOSITORY" \
        --target "$COMMIT_SHA" \
        --title "${lines[0]}" \
        --generate-notes

      for pkg in "$PACKAGE_FOLDER"/*.nupkg; do
          gh release upload "$RELEASE_TAG" "$pkg" --repo "$REPOSITORY" --clobber
      done
    env:
      COMMIT_SHA: ${{ inputs.commitSha }}
      GITHUB_TOKEN: ${{ inputs.gitHubToken }}
      PACKAGE_FOLDER: ${{ inputs.packageFolder }}
      RELEASE_TAG: ${{ inputs.tag }}
      RELEASE_TITLE: ${{ inputs.title }}
      REPOSITORY: ${{ inputs.repository }}
