name: dotnet build
description: Builds the packages and ensures their quality by running tests.
inputs:
  assemblyVersion:
    description: The scaler assembly's version.
    required: true
  buildConfiguration:
    default: Debug
    description: The dotnet build configuration.
    required: false
  fileVersion:
    description: The scaler assembly's file version.
    required: true
  informationalVersion:
    description: The scaler assembly's informational version.
    required: true

runs:
  using: composite
  steps:
  - name: Build
    shell: bash
    run: |
      dotnet build "./Microsoft.Health.sln" \
        -c "${{ inputs.buildConfiguration }}" \
        "-p:ContinuousIntegrationBuild=true;AssemblyVersion=${{ inputs.assemblyVersion }};FileVersion=${{ inputs.fileVersion }};InformationalVersion=${{ inputs.informationalVersion }}" \
        -warnaserror

  - name: Test
    shell: bash
    run: |
      dotnet test "./Microsoft.Health.sln" \
        -c "${{ inputs.buildConfiguration }}" \
        "-p:ContinuousIntegrationBuild=true;AssemblyVersion=${{ inputs.assemblyVersion }};FileVersion=${{ inputs.fileVersion }};InformationalVersion=${{ inputs.informationalVersion }}" \
        -warnaserror \
        --no-build \
        --filter "FullyQualifiedName!~E2E&FullyQualifiedName!~Integration"
