<Project Sdk="MSTest.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(SupportedFrameworks)</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Security.KeyVault.Keys" />
    <PackageReference Include="NSubstitute" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Microsoft.Health.Encryption\Microsoft.Health.Encryption.csproj" />
  </ItemGroup>

</Project>
