<Project Sdk="MSTest.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(SupportedFrameworks)</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" PrivateAssets="All" />
    <PackageReference Include="NSubstitute" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Microsoft.Health.EventGrid\Microsoft.Health.EventGrid.csproj" />
  </ItemGroup>

</Project>
