<Project Sdk="MSTest.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(SupportedFrameworks)</TargetFrameworks>
    <NoWarn>$(NoWarn);NU1603</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Microsoft.Health.Test.Common\Microsoft.Health.Test.Utilities.csproj" />
  </ItemGroup>

</Project>
