<Project Sdk="MSTest.Sdk">

  <PropertyGroup>
    <Description>Unit tests for common utilities used by Microsoft Health.</Description>
    <TargetFrameworks>$(SupportedFrameworks)</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Medino" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="NSubstitute" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Microsoft.Health.MeasurementUtility\Microsoft.Health.MeasurementUtility.csproj" />
  </ItemGroup>

</Project>