pr:
  branches:
    include:
    - main
  paths:
    exclude:
    - '**/*.md'

trigger: none

resources:
  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

extends:
  template: v1/1ES.Unofficial.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: mshealthagents
      image: MMSUbuntu20.04-1ESPT
      os: linux
    sdl:
      credscan:
        suppressionsFile: '$(Build.SourcesDirectory)\.config\CredScanSuppressions.json'
      sourceAnalysisPool:
        name: mshealthagents
        image: MMSWindows2022-1ESPT
        os: windows

    stages:
    - stage: Validate
      jobs:

      - job: Version
        steps:
        - checkout: self
          fetchDepth: 0
          submodules: false
        - template: /.pipelines/templates/gitversion.yml@self

      - job: Test
        dependsOn:
        - Version
        steps:
        - template: /.pipelines/templates/dotnet-build.yml@self
          parameters:
            assemblyVersion: $[ dependencies.Version.outputs['Metadata.GitVersion.AssemblySemVer'] ]
            fileVersion: $[ dependencies.Version.outputs['Metadata.GitVersion.AssemblySemFileVer'] ]
            informationalVersion: $[ dependencies.Version.outputs['Metadata.GitVersion.InformationalVersion'] ]
        - template: /.pipelines/templates/dotnet-test.yml@self
