name: Packages PR

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
    - '**.md'

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        fetch-depth: 0

    - name: Install .NET SDK
      uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
      with:
        global-json-file: 'global.json'
        dotnet-version: |
          8.x
          9.x

    - name: Version
      id: version
      uses: ./.github/actions/compute-version

    - name: Build
      uses: ./.github/actions/dotnet-build
      with:
        assemblyVersion: ${{ steps.version.outputs.assemblyVersion }}
        buildConfiguration: Release
        fileVersion: ${{ steps.version.outputs.fileVersion }}
        informationalVersion: ${{ steps.version.outputs.informationalVersion }}
